<a href="https://colab.research.google.com/github/analauralopescapeletto-sketch/AULA-CN/blob/main/atividade5_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

ANA LAURA LOPES CAPELETTO 187065

# Exercicio 4

In [1]:
import numpy as np

def gauss_sem_pivoteamento(A, b):
    """
    Resolve Ax = b por eliminação de Gauss SEM pivoteamento.
    Entrada: matriz A (n x n) e vetor b (n).
    Saída: vetor solução x.
    """
    # Converte para float (evita divisão inteira e problemas de tipo)
    A = np.array(A, dtype=float)
    b = np.array(b, dtype=float).reshape(-1, 1)
    n = A.shape[0]

    # 1) Forma a matriz aumentada [A | b]
    Ab = np.hstack((A, b))
    print("Matriz aumentada inicial:")
    print(Ab, "\n")

    # 2) Eliminação: zera os elementos abaixo de cada pivô
    for k in range(n - 1):                      # k = coluna do pivô
        if abs(Ab[k, k]) < 1e-12:               # sem pivoteamento: pivô nulo trava o método
            raise ZeroDivisionError(f"Pivô nulo na posição ({k+1},{k+1}). "
                                    "Seria necessário pivoteamento.")
        for i in range(k + 1, n):               # linhas abaixo do pivô
            m = Ab[i, k] / Ab[k, k]             # multiplicador
            Ab[i, k:] = Ab[i, k:] - m * Ab[k, k:]   # Li <- Li - m*Lk
        print(f"Após eliminar a coluna {k+1}:")
        print(Ab, "\n")

    # Verifica o último pivô
    if abs(Ab[n - 1, n - 1]) < 1e-12:
        raise ZeroDivisionError("Último pivô nulo: sistema sem solução única.")

    # 3) Substituição regressiva
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        soma = np.dot(Ab[i, i + 1:n], x[i + 1:n])   # termos já conhecidos
        x[i] = (Ab[i, n] - soma) / Ab[i, i]

    return x


# ---------- Teste com o sistema do exercício 2 ----------
A = [[ 2,  1, -1],
     [-3, -1,  2],
     [-2,  1,  2]]
b = [8, -11, -3]

x_gauss = gauss_sem_pivoteamento(A, b)
x_numpy = np.linalg.solve(A, b)

print("Solução (Gauss implementado):", x_gauss)
print("Solução (numpy.linalg.solve):", x_numpy)
print("Diferença máxima:", np.max(np.abs(x_gauss - x_numpy)))

Matriz aumentada inicial:
[[  2.   1.  -1.   8.]
 [ -3.  -1.   2. -11.]
 [ -2.   1.   2.  -3.]] 

Após eliminar a coluna 1:
[[ 2.   1.  -1.   8. ]
 [ 0.   0.5  0.5  1. ]
 [ 0.   2.   1.   5. ]] 

Após eliminar a coluna 2:
[[ 2.   1.  -1.   8. ]
 [ 0.   0.5  0.5  1. ]
 [ 0.   0.  -1.   1. ]] 

Solução (Gauss implementado): [ 2.  3. -1.]
Solução (numpy.linalg.solve): [ 2.  3. -1.]
Diferença máxima: 5.551115123125783e-16


Interpretação : O algoritmo implementado reproduz a solução manual do exercício 2, (2, 3, −1), e coincide com numpy.linalg.solve a menos de erros de arredondamento da ordem de 10⁻¹⁶. A diferença desprezível mostra que a implementação está correta. Vale observar que, sem pivoteamento, o método falha se algum pivô for zero (ou muito pequeno, causando instabilidade numérica); neste sistema os pivôs (2, 0,5 e −1) são todos não nulos, então o método funciona.

EXERCICIO 5B

In [2]:
import numpy as np

# Matriz dos coeficientes e vetor independente do modelo térmico
A_term = [[ 4, -1,  0],
          [-1,  4, -1],
          [ 0, -1,  3]]
b_term = [15, 10, 10]

# Resolve com a função implementada no exercício 4 (Gauss sem pivoteamento)
T_gauss = gauss_sem_pivoteamento(A_term, b_term)

# Confere com o numpy
T_numpy = np.linalg.solve(A_term, b_term)

print("Temperaturas (Gauss):", T_gauss)
print("Temperaturas (numpy):", T_numpy)
print("Diferença máxima:", np.max(np.abs(T_gauss - T_numpy)))

Matriz aumentada inicial:
[[ 4. -1.  0. 15.]
 [-1.  4. -1. 10.]
 [ 0. -1.  3. 10.]] 

Após eliminar a coluna 1:
[[ 4.   -1.    0.   15.  ]
 [ 0.    3.75 -1.   13.75]
 [ 0.   -1.    3.   10.  ]] 

Após eliminar a coluna 2:
[[ 4.         -1.          0.         15.        ]
 [ 0.          3.75       -1.         13.75      ]
 [ 0.          0.          2.73333333 13.66666667]] 

Temperaturas (Gauss): [5. 5. 5.]
Temperaturas (numpy): [5. 5. 5.]
Diferença máxima: 0.0


Interpretação: As três temperaturas de equilíbrio são iguais a 5 (T₁ = T₂ = T₃ = 5), o que confere com a resolução manual do item (a). A matriz é diagonalmente dominante (4 > 1, 4 > 2, 3 > 1), então os pivôs ficam sempre diferentes de zero e o Gauss sem pivoteamento funciona bem, concordando com o numpy.linalg.solve.